CREATE TABLE USER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    BIRTH_DATE DATE NOT NULL
);

CREATE TABLE VEHICLE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(9) NOT NULL,
    BRAND VARCHAR(100) NOT NULL,
    MODEL VARCHAR(150) NOT NULL,
    YEAR VARCHAR(20) NOT NULL,
    PRICE VARCHAR(20) NOT NULL,
    CASTER_DAY ENUM("MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY") NOT NULL,
    ACTIVE_CAR_CASTER BOOLEAN NOT NULL,
    ID_USER INT NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES
    USER(ID)
);